# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JSON-RPC-Server-FastCGI
version:      0.02
version_from: lib/JSON/RPC/Server/FastCGI.pm
installdirs:  site
requires:
    CGI::Fast:                     0
    HTTP::Request:                 0
    JSON::RPC::Server::CGI:        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
